model:
  network_name: asr
  network_setting:
    extract_feature: False
    skip_convert: False
    input_type: wave
    extractor_type: fbank
    extractor_setting:
      n_fft: 400
      hop_length: 160
      win_type: hamming
      win_length: 400
      cmvn: feature/misp2021_avsr/cmvn_wave/cmvn_fbank_htk_far_gss.pt
      specaug: True
      apply_time_warp: False
      time_warp_window: 5
      apply_freq_mask: True
      freq_mask_width_range: [0, 15]
      num_freq_mask: 2
      apply_time_mask: True
      time_mask_width_range: [0, 40]
      num_time_mask: 2
      f_min: 0
      f_max: 8000
      n_mels: 40
      sample_rate: 16000
      norm: slaney
      preemphasis_coefficient: 0.97
      vtln: False
      vtln_low: 0
      vtln_high: 8000
      vtln_warp_factor: 1.
    frontend_type: conv1d
    frontend_setting:
      out_channels: 64
      conv1d_kernel: 1
      conv1d_stride: 1
      act_type: prelu
    backbone_type: resnet1d
    backbone_setting:
      block_type: basic1d
      block_num: 2
      act_type: prelu
      hidden_channels: [ 64, 128, 256, 512 ]
      stride: [ 1, 1, 1, 1 ]
      expansion: 1
      downsample_type: avgpool
    fuse_type: cat
    fuse_setting: {}
    backend_type: tcn
    backend_setting:
      hidden_channels: [ 768, 768, 768, 768 ]
      num_classes: 9024
      kernel_size: [ 3, 5, 7 ]
      dropout: 0.2
      act_type: prelu
      dwpw: False
      downsample_type: norm
      consensus_type: none
      consensus_setting: { }

data:
  loader_output:
    items: &input_items [ far_gss_wave, far_gss_classification_9024_0.01 ]
    shapes: &input_shapes [ [ 0 ], [ 0 ]]
    pad_values: &input_pad_values [ 0, 9024 ]
    batch_size: &batch_size 10
    max_batch_size: &max_batch_size 256
  model_input: 
    items: {'wave': 0, 'length': 1}
    gpu_items: [ wave ]
  model_output:
    items: [ posteriori ]
    store_items: {'posteriori': 0}
    store_item2length: {'posteriori': 1}
  loss_input:
    items_from_loader: {'label': 2, 'length': 3}
    items_from_model: {'net_output': 0}
    gpu_items: [ label ]
  train:
    annotate:
      - feature/misp2021_avsr/train_with_gss.json
    repeat: 1
    max_duration: 100
    hop_duration: 6
    # duration_factor: None
    # deleted_keys: None
    items: *input_items
    # key_output: False
    dynamic: True
    batch_size: *batch_size
    max_batch_size: *max_batch_size
    bucket_length_multiplier: 1.1
    shuffle: True
    drop_last: False
    num_workers: 4
    pin_memory: False
    target_shape: *input_shapes
    pad_value: *input_pad_values
  dev:
    annotate:
      - feature/misp2021_avsr/dev_with_gss.json
    repeat: 1
    max_duration: 100
    hop_duration: 6
    # duration_factor: None
    # deleted_keys: None
    items: *input_items
    # key_output: False
    dynamic: True
    batch_size: *batch_size
    max_batch_size: *max_batch_size
    bucket_length_multiplier: 1.1
    shuffle: True
    drop_last: False
    num_workers: 4
    pin_memory: False
    target_shape: *input_shapes
    pad_value: *input_pad_values
  # eval_addition:
  #   annotate:
  #     - feature/misp2021_avsr/eval_addition_with_gss.json
  #   repeat: 1
  #   max_duration: 100
  #   hop_duration: 6
  #   # duration_factor: None
  #   # deleted_keys: None
  #   items: *input_items
  #   # key_output: False
  #   dynamic: True
  #   batch_size: *batch_size
  #   max_batch_size: *max_batch_size
  #   bucket_length_multiplier: 1.1
  #   shuffle: True
  #   drop_last: False
  #   num_workers: 4
  #   pin_memory: False
  #   target_shape: *input_shapes
  #   pad_value: *input_pad_values
  eval:
    annotate:
      - feature/misp2021_avsr/eval_with_gss.json
    repeat: 1
    max_duration: 100
    hop_duration: 6
    # duration_factor: None
    # deleted_keys: None
    items: *input_items
    # key_output: False
    dynamic: True
    batch_size: *batch_size
    max_batch_size: *max_batch_size
    bucket_length_multiplier: 1.1
    shuffle: True
    drop_last: False
    num_workers: 4
    pin_memory: False
    target_shape: *input_shapes
    pad_value: *input_pad_values
  addition:
    annotate:
      - feature/misp2021_avsr/addition_with_gss.json
    repeat: 1
    max_duration: 100
    hop_duration: 6
    # duration_factor: None
    # deleted_keys: None
    items: *input_items
    # key_output: False
    dynamic: True
    batch_size: *batch_size
    max_batch_size: *max_batch_size
    bucket_length_multiplier: 1.1
    shuffle: True
    drop_last: False
    num_workers: 4
    pin_memory: False
    target_shape: *input_shapes
    pad_value: *input_pad_values

optimizer:
  optimizer_type: Adam
  group_num: 1
  force_lr: False
  common_setting:
    lr: 0.0003
    betas: [0.9, 0.999]
    eps: 0.00000001
    weight_decay: 0.0001
    amsgrad: False

scheduler:
  scheduler_type: cosine
  scheduler_setting:
    t_max: 100
    min_lr: 0.
    last_epoch: -1

loss:
  loss_type: ce
  loss_setting:
    label_type: token
    cal_acc: True
    ignore_idx: 9024
    reduction: mean

gradient:
  grad_clip: 5.
